[package]
name = "day5"
version = "0.1.0"
authors = ["Anand Parwal <anand@skylla.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
